# Generated by Django 3.2.5 on 2021-07-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(max_length=10)),
                ('Longitude', models.FloatField(max_length=10)),
                ('temperature', models.FloatField(max_length=5)),
            ],
        ),
    ]
